# NORMALIZATION PROBLEM

In [1]:
import numpy as np

In [3]:
X = np.random.rand(5,5)

In [19]:
mean_X = X.mean()

In [21]:
std_X = X.std()

In [9]:
Z = (X - mean_X) / std_X

In [13]:
np.save('X_normalized.npy',Z)

In [25]:
print("Normalized Array:")
print(X_normalized)

print("Normalized array saved to 'X_normalized.npy'")

Normalized Array:
[[-1.37059385 -1.07142302 -0.9461819   1.10453134 -0.55338472]
 [-0.84568085  1.41172571  0.99379709  1.70109097  1.10319515]
 [ 1.02914526  0.10091212  1.58869072 -0.96845476  0.20668328]
 [-1.32255402 -1.40490696 -0.40299825  0.65652724 -0.43826402]
 [ 0.00771711  0.756653   -0.70039096 -1.1539593   0.51812363]]
Normalized array saved to 'X_normalized.npy'


# DIVISIBLE BY 3 PROBLEM

In [29]:
import numpy as np

In [31]:
numbers = np.arange(1, 101)

In [33]:
sqr = integers**2

In [35]:
A = sqr.reshape(10,10)

In [37]:
div_by_3 = A[A%3==0]

In [39]:
np.save('div_by_3.npy', div_by_3)

In [47]:
print("Squares of the first 100 positive integers:")
print(A)

Squares of the first 100 positive integers:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [51]:
print("Elements in the array that are divisible by 3:")
print(div_by_3)

Elements in the array that are divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
